/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ParqRouteImport } from './routes/parq'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIdRouteImport } from './routes/trainer.$id'
import { Route as SignupProfessionalRouteImport } from './routes/signup/professional'
import { Route as SignupClientRouteImport } from './routes/signup/client'
import { Route as ProfileRecurringRouteImport } from './routes/profile_.recurring'
import { Route as ProfilePersonalRouteImport } from './routes/profile_.personal'
import { Route as ProfilePaymentsRouteImport } from './routes/profile_.payments'
import { Route as ProfileHistoryRouteImport } from './routes/profile_.history'
import { Route as ProfileCouponsRouteImport } from './routes/profile_.coupons'
import { Route as ProWalletRouteImport } from './routes/pro.wallet'
import { Route as ProTermsRouteImport } from './routes/pro.terms'
import { Route as ProSupportRouteImport } from './routes/pro.support'
import { Route as ProSignupRouteImport } from './routes/pro.signup'
import { Route as ProSecurityRouteImport } from './routes/pro.security'
import { Route as ProSchedulesRouteImport } from './routes/pro.schedules'
import { Route as ProReviewsRouteImport } from './routes/pro.reviews'
import { Route as ProRecurringRouteImport } from './routes/pro.recurring'
import { Route as ProProfileRouteImport } from './routes/pro.profile'
import { Route as ProPrivacyRouteImport } from './routes/pro.privacy'
import { Route as ProNotificationsRouteImport } from './routes/pro.notifications'
import { Route as ProHistoryRouteImport } from './routes/pro.history'
import { Route as ProHelpRouteImport } from './routes/pro.help'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as ProCouponsRouteImport } from './routes/pro.coupons'
import { Route as ProChatsRouteImport } from './routes/pro.chats'
import { Route as ProBoostRouteImport } from './routes/pro.boost'
import { Route as ClientTermsRouteImport } from './routes/client.terms'
import { Route as ClientSupportRouteImport } from './routes/client.support'
import { Route as ClientSecurityRouteImport } from './routes/client.security'
import { Route as ClientPrivacyRouteImport } from './routes/client.privacy'
import { Route as ClientHelpRouteImport } from './routes/client.help'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ProChatIdRouteImport } from './routes/pro.chat.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ParqRoute = ParqRouteImport.update({
  id: '/parq',
  path: '/parq',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIdRoute = TrainerIdRouteImport.update({
  id: '/trainer/$id',
  path: '/trainer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupProfessionalRoute = SignupProfessionalRouteImport.update({
  id: '/signup/professional',
  path: '/signup/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupClientRoute = SignupClientRouteImport.update({
  id: '/signup/client',
  path: '/signup/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRecurringRoute = ProfileRecurringRouteImport.update({
  id: '/profile_/recurring',
  path: '/profile/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonalRoute = ProfilePersonalRouteImport.update({
  id: '/profile_/personal',
  path: '/profile/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePaymentsRoute = ProfilePaymentsRouteImport.update({
  id: '/profile_/payments',
  path: '/profile/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile_/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCouponsRoute = ProfileCouponsRouteImport.update({
  id: '/profile_/coupons',
  path: '/profile/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ProWalletRoute = ProWalletRouteImport.update({
  id: '/pro/wallet',
  path: '/pro/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProTermsRoute = ProTermsRouteImport.update({
  id: '/pro/terms',
  path: '/pro/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSupportRoute = ProSupportRouteImport.update({
  id: '/pro/support',
  path: '/pro/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSignupRoute = ProSignupRouteImport.update({
  id: '/pro/signup',
  path: '/pro/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSecurityRoute = ProSecurityRouteImport.update({
  id: '/pro/security',
  path: '/pro/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSchedulesRoute = ProSchedulesRouteImport.update({
  id: '/pro/schedules',
  path: '/pro/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProReviewsRoute = ProReviewsRouteImport.update({
  id: '/pro/reviews',
  path: '/pro/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRecurringRoute = ProRecurringRouteImport.update({
  id: '/pro/recurring',
  path: '/pro/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ProProfileRoute = ProProfileRouteImport.update({
  id: '/pro/profile',
  path: '/pro/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPrivacyRoute = ProPrivacyRouteImport.update({
  id: '/pro/privacy',
  path: '/pro/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProNotificationsRoute = ProNotificationsRouteImport.update({
  id: '/pro/notifications',
  path: '/pro/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProHistoryRoute = ProHistoryRouteImport.update({
  id: '/pro/history',
  path: '/pro/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProHelpRoute = ProHelpRouteImport.update({
  id: '/pro/help',
  path: '/pro/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCouponsRoute = ProCouponsRouteImport.update({
  id: '/pro/coupons',
  path: '/pro/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ProChatsRoute = ProChatsRouteImport.update({
  id: '/pro/chats',
  path: '/pro/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProBoostRoute = ProBoostRouteImport.update({
  id: '/pro/boost',
  path: '/pro/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTermsRoute = ClientTermsRouteImport.update({
  id: '/client/terms',
  path: '/client/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSupportRoute = ClientSupportRouteImport.update({
  id: '/client/support',
  path: '/client/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSecurityRoute = ClientSecurityRouteImport.update({
  id: '/client/security',
  path: '/client/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPrivacyRoute = ClientPrivacyRouteImport.update({
  id: '/client/privacy',
  path: '/client/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHelpRoute = ClientHelpRouteImport.update({
  id: '/client/help',
  path: '/client/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProChatIdRoute = ProChatIdRouteImport.update({
  id: '/pro/chat/$id',
  path: '/pro/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/parq': typeof ParqRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$id': typeof BookingIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/client/help': typeof ClientHelpRoute
  '/client/privacy': typeof ClientPrivacyRoute
  '/client/security': typeof ClientSecurityRoute
  '/client/support': typeof ClientSupportRoute
  '/client/terms': typeof ClientTermsRoute
  '/pro/boost': typeof ProBoostRoute
  '/pro/chats': typeof ProChatsRoute
  '/pro/coupons': typeof ProCouponsRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/help': typeof ProHelpRoute
  '/pro/history': typeof ProHistoryRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/privacy': typeof ProPrivacyRoute
  '/pro/profile': typeof ProProfileRoute
  '/pro/recurring': typeof ProRecurringRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/schedules': typeof ProSchedulesRoute
  '/pro/security': typeof ProSecurityRoute
  '/pro/signup': typeof ProSignupRoute
  '/pro/support': typeof ProSupportRoute
  '/pro/terms': typeof ProTermsRoute
  '/pro/wallet': typeof ProWalletRoute
  '/profile/coupons': typeof ProfileCouponsRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/recurring': typeof ProfileRecurringRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/professional': typeof SignupProfessionalRoute
  '/trainer/$id': typeof TrainerIdRoute
  '/pro/chat/$id': typeof ProChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/parq': typeof ParqRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$id': typeof BookingIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/client/help': typeof ClientHelpRoute
  '/client/privacy': typeof ClientPrivacyRoute
  '/client/security': typeof ClientSecurityRoute
  '/client/support': typeof ClientSupportRoute
  '/client/terms': typeof ClientTermsRoute
  '/pro/boost': typeof ProBoostRoute
  '/pro/chats': typeof ProChatsRoute
  '/pro/coupons': typeof ProCouponsRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/help': typeof ProHelpRoute
  '/pro/history': typeof ProHistoryRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/privacy': typeof ProPrivacyRoute
  '/pro/profile': typeof ProProfileRoute
  '/pro/recurring': typeof ProRecurringRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/schedules': typeof ProSchedulesRoute
  '/pro/security': typeof ProSecurityRoute
  '/pro/signup': typeof ProSignupRoute
  '/pro/support': typeof ProSupportRoute
  '/pro/terms': typeof ProTermsRoute
  '/pro/wallet': typeof ProWalletRoute
  '/profile/coupons': typeof ProfileCouponsRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/recurring': typeof ProfileRecurringRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/professional': typeof SignupProfessionalRoute
  '/trainer/$id': typeof TrainerIdRoute
  '/pro/chat/$id': typeof ProChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/parq': typeof ParqRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/booking/$id': typeof BookingIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/client/help': typeof ClientHelpRoute
  '/client/privacy': typeof ClientPrivacyRoute
  '/client/security': typeof ClientSecurityRoute
  '/client/support': typeof ClientSupportRoute
  '/client/terms': typeof ClientTermsRoute
  '/pro/boost': typeof ProBoostRoute
  '/pro/chats': typeof ProChatsRoute
  '/pro/coupons': typeof ProCouponsRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/help': typeof ProHelpRoute
  '/pro/history': typeof ProHistoryRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/privacy': typeof ProPrivacyRoute
  '/pro/profile': typeof ProProfileRoute
  '/pro/recurring': typeof ProRecurringRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/schedules': typeof ProSchedulesRoute
  '/pro/security': typeof ProSecurityRoute
  '/pro/signup': typeof ProSignupRoute
  '/pro/support': typeof ProSupportRoute
  '/pro/terms': typeof ProTermsRoute
  '/pro/wallet': typeof ProWalletRoute
  '/profile_/coupons': typeof ProfileCouponsRoute
  '/profile_/history': typeof ProfileHistoryRoute
  '/profile_/payments': typeof ProfilePaymentsRoute
  '/profile_/personal': typeof ProfilePersonalRoute
  '/profile_/recurring': typeof ProfileRecurringRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/professional': typeof SignupProfessionalRoute
  '/trainer/$id': typeof TrainerIdRoute
  '/pro/chat/$id': typeof ProChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/notifications'
    | '/parq'
    | '/payment'
    | '/profile'
    | '/ranking'
    | '/reset-password'
    | '/admin/dashboard'
    | '/booking/$id'
    | '/chat/$id'
    | '/client/help'
    | '/client/privacy'
    | '/client/security'
    | '/client/support'
    | '/client/terms'
    | '/pro/boost'
    | '/pro/chats'
    | '/pro/coupons'
    | '/pro/dashboard'
    | '/pro/help'
    | '/pro/history'
    | '/pro/notifications'
    | '/pro/privacy'
    | '/pro/profile'
    | '/pro/recurring'
    | '/pro/reviews'
    | '/pro/schedules'
    | '/pro/security'
    | '/pro/signup'
    | '/pro/support'
    | '/pro/terms'
    | '/pro/wallet'
    | '/profile/coupons'
    | '/profile/history'
    | '/profile/payments'
    | '/profile/personal'
    | '/profile/recurring'
    | '/signup/client'
    | '/signup/professional'
    | '/trainer/$id'
    | '/pro/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/notifications'
    | '/parq'
    | '/payment'
    | '/profile'
    | '/ranking'
    | '/reset-password'
    | '/admin/dashboard'
    | '/booking/$id'
    | '/chat/$id'
    | '/client/help'
    | '/client/privacy'
    | '/client/security'
    | '/client/support'
    | '/client/terms'
    | '/pro/boost'
    | '/pro/chats'
    | '/pro/coupons'
    | '/pro/dashboard'
    | '/pro/help'
    | '/pro/history'
    | '/pro/notifications'
    | '/pro/privacy'
    | '/pro/profile'
    | '/pro/recurring'
    | '/pro/reviews'
    | '/pro/schedules'
    | '/pro/security'
    | '/pro/signup'
    | '/pro/support'
    | '/pro/terms'
    | '/pro/wallet'
    | '/profile/coupons'
    | '/profile/history'
    | '/profile/payments'
    | '/profile/personal'
    | '/profile/recurring'
    | '/signup/client'
    | '/signup/professional'
    | '/trainer/$id'
    | '/pro/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/favorites'
    | '/forgot-password'
    | '/home'
    | '/notifications'
    | '/parq'
    | '/payment'
    | '/profile'
    | '/ranking'
    | '/reset-password'
    | '/admin/dashboard'
    | '/booking/$id'
    | '/chat/$id'
    | '/client/help'
    | '/client/privacy'
    | '/client/security'
    | '/client/support'
    | '/client/terms'
    | '/pro/boost'
    | '/pro/chats'
    | '/pro/coupons'
    | '/pro/dashboard'
    | '/pro/help'
    | '/pro/history'
    | '/pro/notifications'
    | '/pro/privacy'
    | '/pro/profile'
    | '/pro/recurring'
    | '/pro/reviews'
    | '/pro/schedules'
    | '/pro/security'
    | '/pro/signup'
    | '/pro/support'
    | '/pro/terms'
    | '/pro/wallet'
    | '/profile_/coupons'
    | '/profile_/history'
    | '/profile_/payments'
    | '/profile_/personal'
    | '/profile_/recurring'
    | '/signup/client'
    | '/signup/professional'
    | '/trainer/$id'
    | '/pro/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  ParqRoute: typeof ParqRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BookingIdRoute: typeof BookingIdRoute
  ChatIdRoute: typeof ChatIdRoute
  ClientHelpRoute: typeof ClientHelpRoute
  ClientPrivacyRoute: typeof ClientPrivacyRoute
  ClientSecurityRoute: typeof ClientSecurityRoute
  ClientSupportRoute: typeof ClientSupportRoute
  ClientTermsRoute: typeof ClientTermsRoute
  ProBoostRoute: typeof ProBoostRoute
  ProChatsRoute: typeof ProChatsRoute
  ProCouponsRoute: typeof ProCouponsRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProHelpRoute: typeof ProHelpRoute
  ProHistoryRoute: typeof ProHistoryRoute
  ProNotificationsRoute: typeof ProNotificationsRoute
  ProPrivacyRoute: typeof ProPrivacyRoute
  ProProfileRoute: typeof ProProfileRoute
  ProRecurringRoute: typeof ProRecurringRoute
  ProReviewsRoute: typeof ProReviewsRoute
  ProSchedulesRoute: typeof ProSchedulesRoute
  ProSecurityRoute: typeof ProSecurityRoute
  ProSignupRoute: typeof ProSignupRoute
  ProSupportRoute: typeof ProSupportRoute
  ProTermsRoute: typeof ProTermsRoute
  ProWalletRoute: typeof ProWalletRoute
  ProfileCouponsRoute: typeof ProfileCouponsRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfilePaymentsRoute: typeof ProfilePaymentsRoute
  ProfilePersonalRoute: typeof ProfilePersonalRoute
  ProfileRecurringRoute: typeof ProfileRecurringRoute
  SignupClientRoute: typeof SignupClientRoute
  SignupProfessionalRoute: typeof SignupProfessionalRoute
  TrainerIdRoute: typeof TrainerIdRoute
  ProChatIdRoute: typeof ProChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parq': {
      id: '/parq'
      path: '/parq'
      fullPath: '/parq'
      preLoaderRoute: typeof ParqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/$id': {
      id: '/trainer/$id'
      path: '/trainer/$id'
      fullPath: '/trainer/$id'
      preLoaderRoute: typeof TrainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/professional': {
      id: '/signup/professional'
      path: '/signup/professional'
      fullPath: '/signup/professional'
      preLoaderRoute: typeof SignupProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/client': {
      id: '/signup/client'
      path: '/signup/client'
      fullPath: '/signup/client'
      preLoaderRoute: typeof SignupClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/recurring': {
      id: '/profile_/recurring'
      path: '/profile/recurring'
      fullPath: '/profile/recurring'
      preLoaderRoute: typeof ProfileRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/personal': {
      id: '/profile_/personal'
      path: '/profile/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof ProfilePersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/payments': {
      id: '/profile_/payments'
      path: '/profile/payments'
      fullPath: '/profile/payments'
      preLoaderRoute: typeof ProfilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/history': {
      id: '/profile_/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/coupons': {
      id: '/profile_/coupons'
      path: '/profile/coupons'
      fullPath: '/profile/coupons'
      preLoaderRoute: typeof ProfileCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/wallet': {
      id: '/pro/wallet'
      path: '/pro/wallet'
      fullPath: '/pro/wallet'
      preLoaderRoute: typeof ProWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/terms': {
      id: '/pro/terms'
      path: '/pro/terms'
      fullPath: '/pro/terms'
      preLoaderRoute: typeof ProTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/support': {
      id: '/pro/support'
      path: '/pro/support'
      fullPath: '/pro/support'
      preLoaderRoute: typeof ProSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/signup': {
      id: '/pro/signup'
      path: '/pro/signup'
      fullPath: '/pro/signup'
      preLoaderRoute: typeof ProSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/security': {
      id: '/pro/security'
      path: '/pro/security'
      fullPath: '/pro/security'
      preLoaderRoute: typeof ProSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/schedules': {
      id: '/pro/schedules'
      path: '/pro/schedules'
      fullPath: '/pro/schedules'
      preLoaderRoute: typeof ProSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/reviews': {
      id: '/pro/reviews'
      path: '/pro/reviews'
      fullPath: '/pro/reviews'
      preLoaderRoute: typeof ProReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/recurring': {
      id: '/pro/recurring'
      path: '/pro/recurring'
      fullPath: '/pro/recurring'
      preLoaderRoute: typeof ProRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/profile': {
      id: '/pro/profile'
      path: '/pro/profile'
      fullPath: '/pro/profile'
      preLoaderRoute: typeof ProProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/privacy': {
      id: '/pro/privacy'
      path: '/pro/privacy'
      fullPath: '/pro/privacy'
      preLoaderRoute: typeof ProPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/notifications': {
      id: '/pro/notifications'
      path: '/pro/notifications'
      fullPath: '/pro/notifications'
      preLoaderRoute: typeof ProNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/history': {
      id: '/pro/history'
      path: '/pro/history'
      fullPath: '/pro/history'
      preLoaderRoute: typeof ProHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/help': {
      id: '/pro/help'
      path: '/pro/help'
      fullPath: '/pro/help'
      preLoaderRoute: typeof ProHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/coupons': {
      id: '/pro/coupons'
      path: '/pro/coupons'
      fullPath: '/pro/coupons'
      preLoaderRoute: typeof ProCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/chats': {
      id: '/pro/chats'
      path: '/pro/chats'
      fullPath: '/pro/chats'
      preLoaderRoute: typeof ProChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/boost': {
      id: '/pro/boost'
      path: '/pro/boost'
      fullPath: '/pro/boost'
      preLoaderRoute: typeof ProBoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/terms': {
      id: '/client/terms'
      path: '/client/terms'
      fullPath: '/client/terms'
      preLoaderRoute: typeof ClientTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/support': {
      id: '/client/support'
      path: '/client/support'
      fullPath: '/client/support'
      preLoaderRoute: typeof ClientSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/security': {
      id: '/client/security'
      path: '/client/security'
      fullPath: '/client/security'
      preLoaderRoute: typeof ClientSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/privacy': {
      id: '/client/privacy'
      path: '/client/privacy'
      fullPath: '/client/privacy'
      preLoaderRoute: typeof ClientPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/help': {
      id: '/client/help'
      path: '/client/help'
      fullPath: '/client/help'
      preLoaderRoute: typeof ClientHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/chat/$id': {
      id: '/pro/chat/$id'
      path: '/pro/chat/$id'
      fullPath: '/pro/chat/$id'
      preLoaderRoute: typeof ProChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  ParqRoute: ParqRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BookingIdRoute: BookingIdRoute,
  ChatIdRoute: ChatIdRoute,
  ClientHelpRoute: ClientHelpRoute,
  ClientPrivacyRoute: ClientPrivacyRoute,
  ClientSecurityRoute: ClientSecurityRoute,
  ClientSupportRoute: ClientSupportRoute,
  ClientTermsRoute: ClientTermsRoute,
  ProBoostRoute: ProBoostRoute,
  ProChatsRoute: ProChatsRoute,
  ProCouponsRoute: ProCouponsRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProHelpRoute: ProHelpRoute,
  ProHistoryRoute: ProHistoryRoute,
  ProNotificationsRoute: ProNotificationsRoute,
  ProPrivacyRoute: ProPrivacyRoute,
  ProProfileRoute: ProProfileRoute,
  ProRecurringRoute: ProRecurringRoute,
  ProReviewsRoute: ProReviewsRoute,
  ProSchedulesRoute: ProSchedulesRoute,
  ProSecurityRoute: ProSecurityRoute,
  ProSignupRoute: ProSignupRoute,
  ProSupportRoute: ProSupportRoute,
  ProTermsRoute: ProTermsRoute,
  ProWalletRoute: ProWalletRoute,
  ProfileCouponsRoute: ProfileCouponsRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfilePaymentsRoute: ProfilePaymentsRoute,
  ProfilePersonalRoute: ProfilePersonalRoute,
  ProfileRecurringRoute: ProfileRecurringRoute,
  SignupClientRoute: SignupClientRoute,
  SignupProfessionalRoute: SignupProfessionalRoute,
  TrainerIdRoute: TrainerIdRoute,
  ProChatIdRoute: ProChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
